# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 20:04
from __future__ import unicode_literals

import acount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='uid',
            field=models.IntegerField(default=acount.models.psrandgen_trans, editable=False, unique=True, verbose_name='Transaction identifier'),
        ),
    ]
